spring:
  mail:
    host: smtp.gmail.com
    password: jymohhdvojdczcsi
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: shubhh1181@gmail.com